spring.application.name=jwtDemo

spring.datasource.url=jdbc:mysql://localhost:3306/sales_savvy_db
spring.datasource.username=root
spring.datasource.password=Shibili@1412

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt.secret=CryUa093wtOzGvqJAUTjJLpD7ByqxC141OnjmftRtfS
app.jwt.expiration-ms=36000000

razorpay.key-id=rzp_test_TOs5KEYmjye8m0
razorpay.key-secret=EJQRacCZXDkVsOWkfeec6QHC
razorpay.currency=INR

